#include "speculative.h"

#include "common.h"
#include "ggml.h"
#include "llama.h"
#include "log.h"
#include "ngram-cache.h"
#include "ngram-map.h"
#include "ngram-mod.h"
#include "sampling.h"

#include <algorithm>
#include <cstring>
#include <iomanip>
#include <map>

#define SPEC_VOCAB_MAX_SIZE_DIFFERENCE  128
#define SPEC_VOCAB_CHECK_START_TOKEN_ID 5

const std::vector<enum common_speculative_type> common_speculative_types = {
    COMMON_SPECULATIVE_TYPE_NONE,
    COMMON_SPECULATIVE_TYPE_DRAFT,
    COMMON_SPECULATIVE_TYPE_EAGLE3,
    COMMON_SPECULATIVE_TYPE_MTP,
    COMMON_SPECULATIVE_TYPE_NGRAM_SIMPLE,
    COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K,
    COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K4V,
    COMMON_SPECULATIVE_TYPE_NGRAM_MOD,
    COMMON_SPECULATIVE_TYPE_NGRAM_CACHE
};

const std::map<std::string, enum common_speculative_type> common_speculative_type_from_name_map = {
    {"none",          COMMON_SPECULATIVE_TYPE_NONE},
    {"draft",         COMMON_SPECULATIVE_TYPE_DRAFT},
    {"eagle3",        COMMON_SPECULATIVE_TYPE_EAGLE3},
    {"mtp",           COMMON_SPECULATIVE_TYPE_MTP},
    {"ngram_simple",  COMMON_SPECULATIVE_TYPE_NGRAM_SIMPLE},
    {"ngram_map_k",   COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K},
    {"ngram_map_k4v", COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K4V},
    {"ngram_mod",     COMMON_SPECULATIVE_TYPE_NGRAM_MOD},
    {"ngram_cache",   COMMON_SPECULATIVE_TYPE_NGRAM_CACHE}
};

struct common_speculative_config {
    common_speculative_type type;
    common_params_speculative params;

    common_speculative_config(common_speculative_type t,
            const common_params_speculative & p = common_params_speculative{}) : type(t), params(p) {}
};

static bool common_speculative_are_compatible(
    const llama_model * model_tgt,
    const llama_model * model_dft) {
    const llama_vocab * vocab_tgt = llama_model_get_vocab(model_tgt);
    const llama_vocab * vocab_dft = llama_model_get_vocab(model_dft);

    const bool vocab_type_tgt = llama_vocab_type(vocab_tgt);
    LOG_DBG("%s: vocab_type tgt: %d\n", __func__, vocab_type_tgt);

    const bool vocab_type_dft = llama_vocab_type(vocab_dft);
    LOG_DBG("%s: vocab_type dft: %d\n", __func__, vocab_type_dft);

    if (vocab_type_tgt != vocab_type_dft) {
        LOG_DBG("%s: draft model vocab type must match target model to use speculation but ", __func__);
        LOG_DBG("vocab_type_dft = %d while vocab_type_tgt = %d\n", vocab_type_dft, vocab_type_tgt);
        return false;
    }

    if (
        llama_vocab_get_add_bos(vocab_tgt) != llama_vocab_get_add_bos(vocab_dft) ||
        llama_vocab_get_add_eos(vocab_tgt) != llama_vocab_get_add_eos(vocab_dft) ||
        llama_vocab_bos(vocab_tgt) != llama_vocab_bos(vocab_dft) ||
        llama_vocab_eos(vocab_tgt) != llama_vocab_eos(vocab_dft)
    ) {
        LOG_DBG("%s: draft model special tokens must match target model to use speculation\n", __func__);
        return false;
    }

    {
        const int n_vocab_tgt = llama_vocab_n_tokens(vocab_tgt);
        const int n_vocab_dft = llama_vocab_n_tokens(vocab_dft);
        const int vocab_diff  = n_vocab_tgt > n_vocab_dft
            ? n_vocab_tgt - n_vocab_dft
            : n_vocab_dft - n_vocab_tgt;

        if (vocab_diff > SPEC_VOCAB_MAX_SIZE_DIFFERENCE) {
            LOG_DBG("%s: draft model vocab must closely match target model to use speculation but ", __func__);
            LOG_DBG("target vocab size %d does not match draft vocab size %d - difference %d, max allowed %d\n",
                    n_vocab_tgt, llama_vocab_n_tokens(vocab_dft), vocab_diff, SPEC_VOCAB_MAX_SIZE_DIFFERENCE);
            return false;
        }

        for (int i = SPEC_VOCAB_CHECK_START_TOKEN_ID; i < std::min(n_vocab_tgt, n_vocab_dft); ++i) {
            const char * token_text_tgt = llama_vocab_get_text(vocab_tgt, i);
            const char * token_text_dft = llama_vocab_get_text(vocab_dft, i);

            if (std::strcmp(token_text_tgt, token_text_dft) != 0) {
                LOG_DBG("%s: draft model vocab must match target model to use speculation but ", __func__);
                LOG_DBG("token %d content differs - target '%s', draft '%s'\n", i,
                        common_token_to_piece(vocab_tgt, i).c_str(),
                        common_token_to_piece(vocab_dft, i).c_str());
                return false;
            }
        }
    }

    return true;
}

// state of an implementation of speculative decoding
//
// each implementation has a unique type and a state that is implementation-specific
// in a subclass of common_speculative_state
struct common_speculative_state {
    const enum common_speculative_type type;

    size_t n_call_begin  = 0; // number of times this implementation was called for refresh.
    size_t n_call_draft  = 0; // number of times this implementation was called for generation.
    size_t n_call_accept = 0; // number of times this implementation was called for accumulation.

    size_t n_gen_drafts = 0; // number of times a draft or part was generated by this implementation.
    size_t n_acc_drafts = 0; // number of times a draft or part was accepted by the target model.
    size_t n_gen_tokens = 0; // number of tokens generated by this implementation.
    size_t n_acc_tokens = 0; // number of tokens accepted by the target model.

    // TODO: track performance of most recent calls
    const bool gen_perf = true; // whether to generate performance stats.

    int64_t t_begin_us  = 0; // total time spent in refresh of this implementation in microseconds.
    int64_t t_draft_us  = 0; // total time spent in generating drafts in this implementation in microseconds.
    int64_t t_accept_us = 0; // total time spent in accumulation of this implementation in microseconds.

    common_speculative_state(enum common_speculative_type type) : type(type) {}

    virtual ~common_speculative_state() = default;

    virtual void begin(const llama_tokens & prompt) = 0;

    virtual void draft(
            const common_params_speculative & params,
            const llama_tokens & prompt_tgt,
            llama_token id_last,
            llama_tokens & result) = 0;

    virtual void accept(uint16_t n_accepted) = 0;

    // Hidden-state speculators (MTP, EAGLE) need to know which target output row belongs to the
    // token preceding id_last; it is the count of draft tokens the target just accepted. Nothing
    // else uses it, so the default is to ignore it.
    virtual void set_target_output_idx(int32_t i) { GGML_UNUSED(i); }
};

struct common_speculative_state_draft : public common_speculative_state {
    llama_context * ctx_tgt; // only used for retokenizing from ctx_dft
    llama_context * ctx_dft;

    common_sampler * smpl;

    llama_batch  batch;
    llama_tokens prompt_dft;

    bool vocab_cmpt = true; // whether retokenization is needed
    std::unordered_map<std::string, std::string> vocab_map;

    common_speculative_state_draft(
            enum common_speculative_type type,
            llama_context * ctx_tgt,
            llama_context * ctx_dft,
            const std::vector<std::pair<std::string, std::string>> & replacements)
        : common_speculative_state(type)
        , ctx_tgt(ctx_tgt)
        , ctx_dft(ctx_dft)
    {
        batch = llama_batch_init(llama_n_batch(ctx_dft), 0, 1);
        smpl = nullptr;

        // TODO: optimize or pass from outside?
        // {
        //     common_params_sampling params;
        //     params.no_perf = false;
        //
        //     params.top_k = 40;
        //     params.top_p = 0.9;
        //
        //     params.samplers = {
        //         COMMON_SAMPLER_TYPE_TOP_K,
        //         COMMON_SAMPLER_TYPE_TOP_P,
        //         COMMON_SAMPLER_TYPE_INFILL,
        //     };
        //
        //     result->smpl = common_sampler_init(llama_get_model(ctx_dft), params);
        // }
        {
            common_params_sampling params;
            params.no_perf = false;
            params.top_k = 10;
            params.samplers = {
                COMMON_SAMPLER_TYPE_TOP_K,
            };

            smpl = common_sampler_init(llama_get_model(ctx_dft), params);
        }

        vocab_cmpt = common_speculative_are_compatible(llama_get_model(ctx_tgt), llama_get_model(ctx_dft));
        LOG_DBG("vocab_cmpt = %d\n", vocab_cmpt);

        if (!vocab_cmpt) {
            LOG_WRN("the target and draft vocabs are not compatible - tokens will be translated between the two\n");

            for (const auto & pair : replacements) {
                vocab_map[pair.first] = pair.second;
            }
        }
    }

    ~common_speculative_state_draft() override {
        llama_perf_context_print(ctx_dft);

        llama_free(ctx_dft);

        common_sampler_free(smpl);

        llama_batch_free(batch);
    }

    void begin(const llama_tokens & prompt) override {
        GGML_UNUSED(prompt);
    }

    void draft(
            const common_params_speculative & params,
            const llama_tokens & prompt_tgt,
            llama_token id_last,
            llama_tokens & result) override {
        auto * spec = this;

        auto & batch      = spec->batch;
        auto & ctx_tgt    = spec->ctx_tgt;
        auto & ctx_dft    = spec->ctx_dft;
        auto & smpl       = spec->smpl;
        auto & prompt_dft = spec->prompt_dft;

        auto * mem_dft = llama_get_memory(ctx_dft);

        int reuse_i = 0;
        int reuse_n = 0;

        const int n_ctx = llama_n_ctx(ctx_dft) - params.n_max;

        llama_tokens prompt_cnv;
        if (!spec->vocab_cmpt) {
            std::string text;

            text = common_detokenize(ctx_tgt, prompt_tgt, true);
            text = replace_to_dft(text);

            LOG_DBG("%s: main->draft detokenized string: '%s'\n", __func__, text.c_str());

            prompt_cnv = common_tokenize(ctx_dft, text, false, true);

            // convert id_last to draft vocab. llama_detokenize is called directly to avoid an allocation
            const auto * model_tgt = llama_get_model(ctx_tgt);
            const auto * vocab_tgt = llama_model_get_vocab(model_tgt);

            int32_t n_chars = llama_detokenize(vocab_tgt, &id_last, 1, nullptr, 0, false, false);
            GGML_ASSERT(n_chars < 0 && "failed to detokenize id_last");

            text.resize(-n_chars);
            llama_detokenize(vocab_tgt, &id_last, 1, text.data(), text.size(), false, false);
            text = replace_to_dft(text);

            LOG_DBG("main->draft detokenized id_last(%d): '%s'\n", id_last, text.c_str());
            id_last = common_tokenize(ctx_dft, text, false, true)[0];
        }

        const llama_tokens & prompt_cur = spec->vocab_cmpt ? prompt_tgt : prompt_cnv;

        const int i_start = std::max<int>(0, (int) prompt_cur.size() - n_ctx);

        // reuse as much as possible from the old draft context
        // ideally, the draft context should be as big as the target context and we will always reuse the entire prompt
        for (int i = 0; i < (int) prompt_dft.size(); ++i) {
            int cur = 0;
            while (i_start + cur < (int) prompt_cur.size() &&
                    i       + cur < (int) prompt_dft.size() &&
                    prompt_cur[i_start + cur] == prompt_dft[i + cur]) {
                cur++;
            }

            if ((cur >= 256 || n_ctx >= (int) prompt_cur.size()) && cur > reuse_n) {
                reuse_i = i;
                reuse_n = cur;
            }
        }

        LOG_DBG("%s: reuse_i = %d, reuse_n = %d, prompt = %d\n", __func__, reuse_i, reuse_n, (int) prompt_dft.size());

        result.clear();
        result.reserve(params.n_max);

        if (reuse_n == 0) {
            llama_memory_clear(mem_dft, false);
            prompt_dft.clear();
        } else {
            // this happens when a previous draft has been discarded (for example, due to being too small), but the
            // target model agreed with it. in this case, we simply pass back the previous results to save compute
            if (reuse_i + reuse_n < (int) prompt_dft.size() && prompt_dft[reuse_i + reuse_n] == id_last) {
                for (int i = reuse_i + reuse_n + 1; i < (int) prompt_dft.size(); ++i) {
                    result.push_back(prompt_dft[i]);

                    if (params.n_max <= (int) result.size()) {
                        break;
                    }
                }

                return;
            }

            if (reuse_i > 0) {
                llama_memory_seq_rm (mem_dft, 0, 0, reuse_i);
                llama_memory_seq_add(mem_dft, 0, reuse_i, -1, -reuse_i);

                prompt_dft.erase(prompt_dft.begin(), prompt_dft.begin() + reuse_i);
            }

            if (reuse_n < (int) prompt_dft.size()) {
                llama_memory_seq_rm (mem_dft, 0, reuse_n, -1);
                prompt_dft.erase(prompt_dft.begin() + reuse_n, prompt_dft.end());
            }
        }

        // prepare a batch to evaluate any new tokens in the prompt
        common_batch_clear(batch);

        for (size_t i = i_start + reuse_n; i < prompt_cur.size(); ++i) {
            //LOG_DBG("i = %d, i_start = %d, reuse_n = %d, i - i_start = %d, id = %6d\n", i, i_start, reuse_n, i - i_start, prompt_cur[i]);
            common_batch_add(batch, prompt_cur[i], i - i_start, { 0 }, false);

            prompt_dft.push_back(prompt_cur[i]);
        }

        // we should rarely end-up here during normal decoding
        if (batch.n_tokens > 0) {
            //LOG_DBG("%s: draft prompt batch: %s\n", __func__, string_from(ctx, batch).c_str());

            llama_decode(ctx_dft, batch);
        }

        const llama_pos n_past = prompt_dft.size();

        LOG_DBG("%s: n_past = %d\n", __func__, n_past);

        common_batch_clear(batch);
        common_batch_add  (batch, id_last, n_past, { 0 }, true);

        prompt_dft.push_back(id_last);

        LOG_DBG("%s: draft prompt: %s\n", __func__, string_from(ctx_dft, prompt_dft).c_str());

        llama_decode(ctx_dft, batch);

        common_sampler_reset(smpl);

        // sample n_draft tokens from the draft model
        for (int i = 0; i < params.n_max; ++i) {
            common_batch_clear(batch);

            common_sampler_sample(smpl, ctx_dft, 0, true);

            const auto * cur_p = common_sampler_get_candidates(smpl, true);

            for (int k = 0; k < std::min(3, (int) cur_p->size); ++k) {
                LOG_DBG(" - draft candidate %3d, pos %3d: %6d (%8.3f) '%s'\n",
                        k, i, cur_p->data[k].id, cur_p->data[k].p, common_token_to_piece(ctx_dft, cur_p->data[k].id).c_str());
            }

            // add drafted token for each sequence
            const llama_token id = cur_p->data[0].id;

            common_sampler_accept(smpl, id, true);

            result.push_back(id);

            if (params.n_max <= (int) result.size()) {
                break;
            }

            // only collect very high-confidence draft tokens
            if (cur_p->data[0].p < params.p_min) {
                break;
            }

            common_batch_add(batch, id, n_past + i + 1, { 0 }, true);

            // evaluate the drafted tokens on the draft model
            llama_decode(ctx_dft, batch);

            prompt_dft.push_back(id);
        }

        if (!spec->vocab_cmpt) {
            std::string detokenized = common_detokenize(ctx_dft, result, true);
            detokenized = replace_to_tgt(detokenized);
            LOG_DBG("draft->main detokenized string: '%s'\n", detokenized.c_str());
            result = common_tokenize(ctx_tgt, detokenized, false, true);
            if (result.size() > (size_t)params.n_max) {
                result.resize(params.n_max);
            }
        }
    }

    void accept(uint16_t n_accepted) override {
        // noop
        GGML_UNUSED(n_accepted);
    }

    std::string replace_to_dft(const std::string & input) const {
        std::string result = input;

        for (const auto & pair : this->vocab_map) {
            size_t pos = result.find(pair.first);
            while (pos != std::string::npos) {
                result.replace(pos, pair.first.length(), pair.second);
                pos = result.find(pair.first, pos + pair.second.length());
            }
        }

        return result;
    }

    std::string replace_to_tgt(const std::string & input) const {
        std::string result = input;

        for (const auto & pair : this->vocab_map) {
            size_t pos = result.find(pair.second);
            while (pos != std::string::npos) {
                result.replace(pos, pair.second.length(), pair.first);
                pos = result.find(pair.second, pos + pair.first.length());
            }
        }

        return result;
    }
};

struct common_speculative_state_eagle3 : public common_speculative_state {
    common_speculative_state_eagle3(enum common_speculative_type type) : common_speculative_state(type) {}

    void begin(const llama_tokens & prompt) override {
        GGML_UNUSED(prompt);
    }

    void draft(
            const common_params_speculative & params,
            const llama_tokens & prompt_tgt,
            llama_token id_last,
            llama_tokens & draft_tokens) override {
        // TODO: implement
        GGML_UNUSED(params);
        GGML_UNUSED(prompt_tgt);
        GGML_UNUSED(id_last);
        GGML_UNUSED(draft_tokens);
    }

    void accept(uint16_t n_accepted) override {
        // noop
        GGML_UNUSED(n_accepted);
    }
};


// Is this draft model GLM-5.3's native MTP module, repackaged by scripts/make_mtp_draft.py?
static bool common_speculative_is_mtp(const llama_model * model_dft) {
    if (!model_dft) {
        return false;
    }

    char buf[64] = {0};
    const int32_t n = llama_model_meta_val_str(model_dft, "general.architecture", buf, sizeof(buf));

    return n > 0 && strcmp(buf, "glm5-next-mtp") == 0;
}

// Speculative decoding with a Multi-Token Prediction head.
//
// Unlike a draft model, an MTP module is not a small language model: it cannot predict anything
// on its own. Every step it consumes the hidden state that the *target* produced for the
// preceding token, so the two models are coupled at every decode rather than merely agreeing on
// a vocabulary. That coupling is the whole reason it drafts well from a single layer - the
// target's 45 layers have already encoded the context into the vector it is handed.
//
// Reference: vllm/model_executor/models/glm4_moe_mtp.py.
//
// Two consequences shape the code below:
//
//   * The draft's own KV cache holds only the tokens this speculator has itself decoded. Hidden
//     states for the prompt were never computed - the target emits one only for the position it
//     was asked to output - so there is nothing to seed them with. This costs less than it
//     sounds: GLM-5.3's MLA is NoPE, so a gap in the cache is not a positional inconsistency,
//     merely fewer keys, and the context the module actually relies on arrives through h_prev.
//
//   * At depth > 1 the module feeds on its OWN output rather than the target's. That output is
//     the pre-shared_head_norm tensor, which is why the draft graph exposes it as t_embd; using
//     the post-norm value would silently degrade every draft past the first.
struct common_speculative_state_mtp : public common_speculative_state {
    llama_context * ctx_tgt;
    llama_context * ctx_dft;

    common_sampler * smpl;
    llama_batch      batch;

    // Number of cells the draft KV holds that the target has committed to. Everything at or
    // after this position is last round's speculation and is dropped before drafting again.
    int32_t n_dft = 0;

    // Which target output row carries the hidden state for the token preceding id_last. The
    // caller knows it (it is the number of draft tokens the target accepted); -1 means "the
    // last row", which is the right answer both on the first call and when every draft was
    // accepted.
    int32_t tgt_out_idx = -1;

    std::vector<float> h_buf;

    // Whether h_buf holds the hidden state for the current round. It is filled in
    // set_target_output_idx() rather than here in draft(), because the target's embeddings buffer
    // does not survive until drafting: on a hybrid target the accepted tokens are replayed on
    // ctx_tgt in between (see common_spec_rollback), which overwrites it. Reading it late would
    // hand the draft head a hidden state from the replay batch instead of the verification batch.
    bool h_valid = false;

    common_speculative_state_mtp(
            enum common_speculative_type type,
            llama_context * ctx_tgt,
            llama_context * ctx_dft)
        : common_speculative_state(type)
        , ctx_tgt(ctx_tgt)
        , ctx_dft(ctx_dft)
    {
        batch = llama_batch_init(llama_n_batch(ctx_dft), 0, 1);

        {
            common_params_sampling sparams;
            sparams.no_perf = false;
            sparams.top_k   = 10;
            sparams.samplers = { COMMON_SAMPLER_TYPE_TOP_K };

            smpl = common_sampler_init(llama_get_model(ctx_dft), sparams);
        }

        // Both contexts must hand back hidden states: the target's feeds depth 1, the draft's
        // feeds every depth after that. llama.cpp extracts embeddings together with logits, so
        // this costs an n_embd-sized row per output and nothing else.
        llama_set_embeddings(ctx_tgt, true);
        llama_set_embeddings(ctx_dft, true);

        // Without this, turning embeddings on would promote every prompt token to an output and
        // allocate a full logits row for each. We only ever read the hidden state of tokens the
        // caller already wanted logits for, so ask for exactly that.
        llama_set_embeddings_outputs_only(ctx_tgt, true);
        llama_set_embeddings_outputs_only(ctx_dft, true);

        h_buf.resize(llama_model_n_embd(llama_get_model(ctx_dft)));
    }

    ~common_speculative_state_mtp() override {
        common_sampler_free(smpl);
        llama_batch_free(batch);
    }

    void begin(const llama_tokens & prompt) override {
        GGML_UNUSED(prompt);

        // A new generation shares nothing with the previous one.
        llama_memory_clear(llama_get_memory(ctx_dft), false);
        n_dft       = 0;
        tgt_out_idx = -1;
        h_valid     = false;
    }

    void draft(
            const common_params_speculative & params,
            const llama_tokens & prompt_tgt,
            llama_token id_last,
            llama_tokens & result) override {
        GGML_UNUSED(prompt_tgt);

        result.clear();
        result.reserve(params.n_max);

        const int n_embd = (int) h_buf.size();

        // Normally set_target_output_idx() has already captured this. It has not on the first
        // draft of a sequence, where the caller has decoded the prompt and never accepted
        // anything, so fall back to reading the target's last output row.
        if (!h_valid) {
            const float * h_tgt = llama_get_embeddings_ith(ctx_tgt, tgt_out_idx);
            if (h_tgt == nullptr) {
                // No hidden state means no draft. Returning empty is not a failure: the caller
                // simply decodes one token the ordinary way, which is strictly better than
                // drafting from a stale or zeroed vector and having the target reject it.
                LOG_DBG("%s: target hidden state unavailable (row %d) - skipping this draft\n",
                        __func__, tgt_out_idx);
                return;
            }
            std::copy(h_tgt, h_tgt + n_embd, h_buf.begin());
        }

        // h_buf is overwritten with draft-side hidden states below, so it must be re-captured
        // before the next round.
        h_valid = false;

        // Drop last round's speculation, keeping the cells the target committed to.
        auto * mem_dft = llama_get_memory(ctx_dft);
        llama_memory_seq_rm(mem_dft, 0, n_dft, -1);

        // Take the write position from the cache rather than from n_dft. The two should agree,
        // but a counter that drifts by one produces "sequence positions must remain consecutive"
        // on the *next* call, at which point the cause is several decodes behind the symptom -
        // and every subsequent draft fails the same way, so a single slip silently turns
        // speculation off for the rest of the generation. Asking the memory module what it
        // actually holds cannot drift.
        const llama_pos pos_max = llama_memory_seq_pos_max(mem_dft, 0);

        common_sampler_reset(smpl);

        llama_token tok = id_last;
        int32_t     pos = pos_max + 1;   // pos_max is -1 on an empty cache, so this starts at 0
        int         n_decoded = 0;

        for (int i = 0; i < params.n_max; ++i) {
            llama_set_mtp_hidden(ctx_dft, h_buf.data(), 1);

            common_batch_clear(batch);
            common_batch_add  (batch, tok, pos, { 0 }, true);

            if (llama_decode(ctx_dft, batch) != 0) {
                // Leave nothing half-written behind: a failed decode that still advanced our
                // bookkeeping would desynchronise every later call. Start the draft cache over
                // instead - it costs this generation's accumulated MTP context and nothing else.
                LOG_ERR("%s: draft decode failed at depth %d (pos %d) - resetting draft cache\n",
                        __func__, i, pos);
                llama_memory_clear(mem_dft, false);
                n_dft = 0;
                return;
            }

            n_decoded++;

            common_sampler_sample(smpl, ctx_dft, 0, true);

            const auto * cur_p = common_sampler_get_candidates(smpl, true);
            const llama_token id = cur_p->data[0].id;

            common_sampler_accept(smpl, id, true);
            result.push_back(id);

            if ((int) result.size() >= params.n_max) {
                break;
            }

            // Drafting is only worth the decode if the module is confident; the target pays for
            // every token it has to reject.
            if (cur_p->data[0].p < params.p_min) {
                break;
            }

            // Depth > 1 conditions on the module's own output. See the note above on why this
            // is the pre-norm tensor.
            const float * h_dft = llama_get_embeddings_ith(ctx_dft, -1);
            if (h_dft == nullptr) {
                break;
            }
            std::copy(h_dft, h_dft + n_embd, h_buf.begin());

            tok = id;
            pos++;
        }

        // The position of id_last is now committed; everything drafted after it is provisional
        // until accept() tells us how much the target kept. If nothing was decoded there is
        // nothing to commit.
        if (n_decoded > 0) {
            n_dft = pos_max + 2;
        }
    }

    void accept(uint16_t n_accepted) override {
        // Draft tokens the target agreed with keep their draft-side KV cells.
        n_dft += n_accepted;
    }

    void set_target_output_idx(int32_t i) override {
        tgt_out_idx = i;

        const float * h_tgt = llama_get_embeddings_ith(ctx_tgt, i);
        if (h_tgt == nullptr) {
            h_valid = false;
            return;
        }

        std::copy(h_tgt, h_tgt + h_buf.size(), h_buf.begin());
        h_valid = true;
    }
};

// state of self-speculation (simple implementation, not ngram-map)
struct common_speculative_state_ngram_simple : public common_speculative_state {
    common_ngram_simple_config config;

    common_speculative_state_ngram_simple(
            enum common_speculative_type type,
            common_ngram_simple_config config)
        : common_speculative_state(type), config(config) {}

    void begin(const llama_tokens & prompt) override {
        GGML_UNUSED(prompt);
    }

    void draft(
            const common_params_speculative & params,
            const llama_tokens & prompt_tgt,
            llama_token id_last,
            llama_tokens & result) override {

        result = common_ngram_simple_draft(config, prompt_tgt, id_last);
        GGML_UNUSED(params);
    }

    void accept(uint16_t n_accepted) override {
        // noop
        GGML_UNUSED(n_accepted);
    }
};

struct common_speculative_state_ngram_map_k : public common_speculative_state {
    // draft ngram map for speculative decoding without draft model
    common_ngram_map map;

    common_speculative_state_ngram_map_k(
            enum common_speculative_type type,
            common_ngram_map map)
        : common_speculative_state(type), map(std::move(map)) {}

    void begin(const llama_tokens & prompt) override {
        common_ngram_map_begin(map, prompt);
    }

    void draft(
            const common_params_speculative & params,
            const llama_tokens & prompt_tgt,
            llama_token id_last,
            llama_tokens & result) override {
        common_ngram_map_draft(map, prompt_tgt, id_last, result);
        GGML_UNUSED(params);
    }

    void accept(uint16_t n_accepted) override {
        common_ngram_map_accept(map, n_accepted);
    }
};

struct common_speculative_state_ngram_mod : public common_speculative_state {
    common_ngram_mod & mod;

    // the last position in the prompt that was added to the ngram container
    size_t i_last = 0;

    // length of the last drafted n‑gram (number of tokens returned by draft)
    size_t n_draft_last = 0;

    // consecutive accept rounds with low acceptance fraction (< 0.5)
    int n_low = 0;

    // enable trace logging if LLAMA_TRACE is set
    const bool verbose;

    common_speculative_state_ngram_mod(enum common_speculative_type type, common_ngram_mod & mod)
        : common_speculative_state(type), mod(mod), verbose(std::getenv("LLAMA_TRACE") != nullptr) {
        static_assert(sizeof(llama_token) == sizeof(common_ngram_mod::entry_t));
    }

    void begin(const llama_tokens & prompt) override {
        i_last = 0;

        n_draft_last = 0;

        const size_t n = mod.get_n();

        if (prompt.size() < n) {
            return;
        }

        for (size_t i = 0; i < prompt.size() - n; ++i) {
            mod.add(prompt.data() + i);
        }

        i_last = prompt.size() - n;

        const double f = (double)mod.get_used() / (double)mod.size();
        LOG_INF("%s: ngram_mod occupancy = %zu/%zu (%.2f)\n", __func__, mod.get_used(), mod.size(), f);

        constexpr double f_thold = 0.25;
        if (f > f_thold) {
            LOG_WRN("%s: ngram_mod occupancy %.2f exceeds threshold (%.2f) - resetting\n", __func__, f, f_thold);

            mod.reset();
        }
    }

    void draft(
            const common_params_speculative & params,
            const llama_tokens & prompt_tgt,
            llama_token id_last,
            llama_tokens & result) override {
        GGML_UNUSED(params);

        n_draft_last = 0;

        const size_t cur_len = prompt_tgt.size();
        if (cur_len < mod.get_n()) {
            return;
        }

        const size_t n = mod.get_n();

        // add new ngrams in chunks
        if (i_last + 32 < cur_len) {
            for (size_t i = i_last; i < cur_len - n; ++i) {
                mod.add(prompt_tgt.data() + i);
            }

            i_last = cur_len - n;
        }

        result.resize(n + params.n_max);
        for (size_t i = 0; i < n - 1; ++i) {
            result[i] = prompt_tgt[cur_len - n + 1 + i];
        }
        result[n - 1] = id_last;

        for (int i = 0; i < params.n_max; ++i) {
            const llama_token token = mod.get(result.data() + i);
            if (token == common_ngram_mod::EMPTY) {
                if (i < params.n_min) {
                    result.clear();
                    return;
                }

                result.resize(n + i);
                break;
            }
            result[n + i] = token;
        }

        // only return the m tokens that were drafted
        for (size_t i = 0; n + i < result.size(); ++i) {
            result[i] = result[n + i];
        }
        result.resize(result.size() - n);

        // store length of drafted n‑gram for later acceptance analysis
        n_draft_last = result.size();
    }

    void accept(uint16_t n_accepted) override {
        if (verbose) {
            LOG_INF("%s: accepted %d tokens from %zu drafted tokens\n", __func__, n_accepted, n_draft_last);
        }

        // compute acceptance fraction if we have a recorded draft length
        if (n_draft_last > 0) {
            const double f_acc = (double)n_accepted / (double)n_draft_last;
            if (f_acc < 0.5) {
                n_low++;
                if (n_low >= 3) {
                    LOG_WRN("%s: low acceptance streak (%d) – resetting ngram_mod\n", __func__, n_low);

                    mod.reset();
                    n_low = 0;
                }
            } else {
                n_low = 0;
            }
        }
    }
};

struct common_speculative_state_ngram_cache : public common_speculative_state {
    uint16_t n_draft;
    bool save_dynamic;
    bool save_static;

    common_ngram_cache ngram_cache_context;
    common_ngram_cache ngram_cache_dynamic;
    common_ngram_cache ngram_cache_static;

    size_t cache_size = 0; // number of tokens in n-gram cache

    common_speculative_state_ngram_cache(
            const enum common_speculative_type type,
            const std::string & path_static,
            const std::string & path_dynamic,
            uint16_t            n_draft,
            bool                save_dynamic,
            bool                save_static)
        : common_speculative_state(type)
        , n_draft(n_draft)
        , save_dynamic(save_dynamic)
        , save_static(save_static)
    {
        if (!path_static.empty()) {
            try {
                ngram_cache_static = common_ngram_cache_load(path_static);
            } catch (...) {
                LOG_ERR("failed to open static lookup cache: %s", path_static.c_str());
                GGML_ABORT("Couldn't read static lookup cache");
            }
        }

        if (!path_dynamic.empty()) {
            try {
                ngram_cache_dynamic = common_ngram_cache_load(path_dynamic);
            } catch (...) {
                LOG_ERR("failed to open dynamic lookup cache: %s", path_dynamic.c_str());
                GGML_ABORT("Couldn't read dynamic lookup cache");
            }
        }
    }

    void begin(const llama_tokens & prompt) override {
        GGML_UNUSED(prompt);
    }

    void draft(
            const common_params_speculative & params,
            const llama_tokens & prompt_tgt,
            llama_token id_last,
            llama_tokens & result) override {
        GGML_UNUSED(params);

        if (cache_size < prompt_tgt.size() + 1) {
            llama_tokens tokens_new;
            tokens_new.reserve(prompt_tgt.size() + 1 - cache_size);
            for (size_t j = cache_size; j < prompt_tgt.size(); ++j) {
                tokens_new.push_back(prompt_tgt[j]);
            }
            tokens_new.push_back(id_last); // add the last token

            // Update context ngram cache with new prompt_tgt:
            common_ngram_cache_update(ngram_cache_context, LLAMA_NGRAM_MIN, LLAMA_NGRAM_MAX,
                    tokens_new, tokens_new.size(), false);
            cache_size = prompt_tgt.size() + 1;
        }

        llama_tokens inp;
        inp.reserve(prompt_tgt.size() + 1);
        for (size_t j = 0; j < prompt_tgt.size(); ++j) {
            inp.push_back(prompt_tgt[j]);
        }
        inp.push_back(id_last);

        result.push_back(id_last);

        common_ngram_cache_draft(inp, result, n_draft, LLAMA_NGRAM_MIN, LLAMA_NGRAM_MAX,
                ngram_cache_context,
                ngram_cache_dynamic,
                ngram_cache_static);

        if (result.size() > 0) {
            // delete first token in result (which is the id_last token)
            result.erase(result.begin());
        }
    }

    void accept(uint16_t n_accepted) override {
        // TODO: noop
        GGML_UNUSED(n_accepted);
    }
};


//
// recurrent-state rollback
//

// Speculative decoding rejects a drafted token by removing it from the target's memory. A model
// whose layers carry a rolling recurrent state cannot do that: the state summarises every token
// seen so far and has no per-token history to rewind to, so llama_memory_recurrent::seq_rm refuses
// any partial removal that touches the final position. That is not a corner case for GLM-5.3 -
// 34 of its 45 layers are KDA linear attention - and it makes speculation impossible for the whole
// hybrid family (Mamba, Jamba, Falcon-H1, Granite-4, ...) no matter how good the draft is.
//
// The way through is to checkpoint the recurrent state before the verification batch and, when
// some drafted tokens turn out to be wrong, restore it and replay the ones that were right. Three
// things keep this cheap:
//
//   - LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY saves the recurrent half only. Its size is fixed by the
//     model (145 MiB for GLM-5.3-Flash: 9.6 MiB of conv state, 136 MiB of delta-net state), not by
//     the context length, so the cost does not grow as the conversation does. The attention KV
//     needs no checkpoint - it rewinds the ordinary way.
//   - Restoring puts the recurrent cell's final position back at pos_start - 1, which makes the
//     ordinary seq_rm legal again: nothing the cell holds is inside the removed range any more.
//     So the attention half is truncated by the very call the caller was already making, and no
//     call site has to learn about any of this.
//   - The replay is skipped entirely when every drafted token is accepted, which is the case that
//     matters most for throughput.
//
// What it costs is one extra forward pass over the accepted tokens on a partial rejection. That is
// the honest price of the architecture; a future refinement could fold those tokens into the next
// verification batch instead of paying for a pass of their own.
struct common_spec_rollback {
    llama_context * ctx    = nullptr;
    llama_seq_id    seq_id = 0;

    std::vector<uint8_t> buf;

    llama_pos    pos_start = -1;  // position of the first token of the verification batch
    llama_tokens fed;             // what was fed there: id_last followed by the draft
    bool         armed     = false;

    // Number of tokens waiting to be replayed onto the restored state, or 0 for none. The restore
    // itself is done as soon as the rejection is known, but the replay is a decode, and a decode
    // overwrites the context's output buffer. With more than one sequence in flight the caller is
    // still sampling other sequences out of that buffer at this point, so the decode has to wait
    // until it is asked for - see common_speculative_flush_rollback().
    int32_t      n_pending = 0;

    llama_batch batch;

    common_spec_rollback(llama_context * ctx, llama_seq_id seq_id, int32_t n_batch)
        : ctx(ctx), seq_id(seq_id), batch(llama_batch_init(n_batch, 0, 1)) {}

    ~common_spec_rollback() {
        llama_batch_free(batch);
    }
};

// Take the checkpoint. Called with the target's memory holding exactly the committed prefix, i.e.
// right before the caller builds the batch of id_last + draft.
static void common_spec_rollback_save(
        common_spec_rollback * rb,
        llama_token            id_last,
        const llama_tokens   & draft) {
    rb->armed = false;

    const size_t n = llama_state_seq_get_size_ext(rb->ctx, rb->seq_id, LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY);
    if (n == 0) {
        LOG_WRN("%s: the target has no recurrent state to checkpoint\n", __func__);
        return;
    }

    if (rb->buf.size() < n) {
        rb->buf.resize(n);
    }

    if (llama_state_seq_get_data_ext(rb->ctx, rb->buf.data(), rb->buf.size(), rb->seq_id, LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY) == 0) {
        LOG_WRN("%s: failed to checkpoint the recurrent state\n", __func__);
        return;
    }

    // Take the write position from the memory rather than from the caller's token count. The two
    // agree, but only the memory is authoritative about where the next token actually lands.
    rb->pos_start = llama_memory_seq_pos_max(llama_get_memory(rb->ctx), rb->seq_id) + 1;

    rb->fed.clear();
    rb->fed.reserve(1 + draft.size());
    rb->fed.push_back(id_last);
    rb->fed.insert(rb->fed.end(), draft.begin(), draft.end());

    rb->armed = true;
}

// Put the sequence back to the accepted prefix. n_accepted is the number of DRAFTED tokens the
// target agreed with, so the batch keeps n_accepted + 1 of the tokens it was given. Returns false
// if the sequence could not be restored, in which case speculation must stop - carrying on against
// a recurrent state that no longer matches the tokens would corrupt the output silently.
static bool common_spec_rollback_apply(common_spec_rollback * rb, int32_t n_accepted) {
    if (!rb->armed) {
        return true;
    }

    rb->armed = false;

    const int32_t n_keep = n_accepted + 1;

    // Nothing was rejected: the state already covers exactly the tokens that were kept.
    if (n_keep >= (int32_t) rb->fed.size()) {
        return true;
    }

    if (llama_state_seq_set_data_ext(rb->ctx, rb->buf.data(), rb->buf.size(), rb->seq_id, LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY) == 0) {
        LOG_ERR("%s: failed to restore the recurrent state\n", __func__);
        return false;
    }

    // Legal now that the recurrent half is back at pos_start - 1; this truncates the attention KV.
    if (!llama_memory_seq_rm(llama_get_memory(rb->ctx), rb->seq_id, rb->pos_start, -1)) {
        LOG_ERR("%s: failed to truncate the memory after restoring the recurrent state\n", __func__);
        return false;
    }

    rb->n_pending = n_keep;

    LOG_DBG("%s: rolled back to pos %d, %d token(s) queued for replay\n", __func__, rb->pos_start, n_keep);

    return true;
}

// Replay the accepted tokens onto the restored state. Must run before anything else touches the
// sequence, and only once the caller has finished reading logits out of the context.
static bool common_spec_rollback_flush(common_spec_rollback * rb) {
    if (rb->n_pending == 0) {
        return true;
    }

    const int32_t n_keep = rb->n_pending;
    rb->n_pending = 0;

    // Between the restore and here the caller may have thrown the sequence away entirely - the
    // server does exactly that when it releases a child task's slot. Replaying onto a sequence
    // that no longer ends where the checkpoint left it would punch a hole in it, so check that it
    // is still the sequence we rolled back before writing to it.
    const llama_pos pos_cur = llama_memory_seq_pos_max(llama_get_memory(rb->ctx), rb->seq_id) + 1;
    if (pos_cur != rb->pos_start) {
        LOG_DBG("%s: sequence moved to pos %d since the rollback to %d - dropping the replay\n",
                __func__, pos_cur, rb->pos_start);
        return true;
    }

    common_batch_clear(rb->batch);
    for (int32_t i = 0; i < n_keep; ++i) {
        // Ask for logits on the last row only. They are discarded - the caller sampled from the
        // verification batch - but a batch that requests no outputs at all is not a shape every
        // path expects, and one row is nothing.
        common_batch_add(rb->batch, rb->fed[i], rb->pos_start + i, { rb->seq_id }, i == n_keep - 1);
    }

    if (llama_decode(rb->ctx, rb->batch) != 0) {
        LOG_ERR("%s: failed to replay %d accepted tokens\n", __func__, n_keep);
        return false;
    }

    LOG_DBG("%s: replayed %d token(s) from pos %d\n", __func__, n_keep, rb->pos_start);

    return true;
}

struct common_speculative {
    std::vector<std::unique_ptr<common_speculative_state>> impls; // list of implementations to use and their states
    common_speculative_state * curr_impl = nullptr; // current implementation in use (for stats)

    // Set only when the target's memory cannot drop rejected tokens on its own.
    std::unique_ptr<common_spec_rollback> rb;

    // Latched if a rollback ever fails. Speculation stays off for the rest of the run rather than
    // producing tokens verified against a state that has drifted from the sequence.
    bool broken = false;
};

static common_ngram_map get_common_ngram_map(const common_speculative_config & config) {
    uint16_t size_key   = config.params.ngram_size_n;
    uint16_t size_value = config.params.ngram_size_m;
    bool     key_only   = (config.type == COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K);
    uint16_t min_hits   = config.params.ngram_min_hits;

    return common_ngram_map(size_key, size_value, key_only, min_hits);
}

static common_speculative_state_ngram_cache create_state_ngram_cache(
        const std::string & path_static, const std::string & path_dynamic,
        const common_speculative_config & config) {
    uint16_t n_draft = 8; // TODO get from config?

    // TODO bool param in common/common.h to set save_static/save_dynamic?
    bool save_static = false;
    bool save_dynamic = false;

    common_speculative_state_ngram_cache state(config.type, path_static, path_dynamic, n_draft, save_static, save_dynamic);

    return state;
}

std::string common_speculative_type_name_str() {
    std::string result;
    for (size_t i = 0; i < common_speculative_types.size(); i++) {
        if (i > 0) {
            result += ", ";
        }
        result += common_speculative_type_to_str(common_speculative_types[i]);
    }
    return result;
}

std::string common_speculative_type_to_str(enum common_speculative_type type) {
    switch (type) {
        case COMMON_SPECULATIVE_TYPE_NONE:          return "none";
        case COMMON_SPECULATIVE_TYPE_DRAFT:         return "draft";
        case COMMON_SPECULATIVE_TYPE_EAGLE3:        return "eagle3";
        case COMMON_SPECULATIVE_TYPE_MTP:           return "mtp";
        case COMMON_SPECULATIVE_TYPE_NGRAM_SIMPLE:  return "ngram_simple";
        case COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K:   return "ngram_map_k";
        case COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K4V: return "ngram_map_k4v";
        case COMMON_SPECULATIVE_TYPE_NGRAM_MOD:     return "ngram_mod";
        case COMMON_SPECULATIVE_TYPE_NGRAM_CACHE:   return "ngram_cache";
        default:                                    return "unknown";
    }
}

enum common_speculative_type common_speculative_type_from_name(const std::string & name) {
    const auto it = common_speculative_type_from_name_map.find(name);
    if (it == common_speculative_type_from_name_map.end()) {
        return COMMON_SPECULATIVE_TYPE_COUNT;
    }
    return it->second;
}

bool common_speculative_is_compat(llama_context * ctx_tgt) {
    auto * mem = llama_get_memory(ctx_tgt);
    if (mem == nullptr) {
        return false;
    }

    bool res = true;

    llama_memory_clear(mem, true);

    // eval 2 tokens to check if the context is compatible
    std::vector<llama_token> tmp;
    tmp.push_back(0);
    tmp.push_back(0);

    int ret = llama_decode(ctx_tgt, llama_batch_get_one(tmp.data(), tmp.size()));
    if (ret != 0) {
        LOG_ERR("%s: llama_decode() failed: %d\n", __func__, ret);
        res = false;
        goto done;
    }

    // try to remove the last tokens
    if (!llama_memory_seq_rm(mem, 0, 1, -1)) {
        // A recurrent or hybrid target refuses this: its rolling state cannot be rewound by a
        // token. That used to be the end of the matter, but it is recoverable - the state can be
        // checkpointed before the verification batch and the accepted tokens replayed onto it.
        // See common_spec_rollback; common_speculative_init arms it for exactly these models.
        if (!llama_model_is_recurrent(llama_get_model(ctx_tgt)) && !llama_model_is_hybrid(llama_get_model(ctx_tgt))) {
            LOG_WRN("%s: the target context does not support partial sequence removal\n", __func__);
            res = false;
            goto done;
        }

        LOG_INF("%s: the target cannot drop rejected tokens directly - speculation will checkpoint "
                "and replay its recurrent state\n", __func__);
    }

done:
    llama_memory_clear(mem, true);
    llama_synchronize(ctx_tgt);

    return res;
}

// initialization of the speculative decoding system
//
common_speculative * common_speculative_init(
        common_params_speculative & params,
        llama_context             * ctx_tgt,
        llama_seq_id                seq_id_tgt) {
    llama_context * ctx_dft = nullptr;
    if (params.model_dft) {
        ctx_dft = llama_init_from_model(params.model_dft, params.cparams_dft);
        if (ctx_dft == nullptr) {
            LOG_ERR("%s", "failed to create draft context\n");
            return nullptr;
        }
    }

    // Compute the implementations to use based on the config and their order of preference
    std::vector<common_speculative_config> configs = {}; // list of speculative configs to try
    {
        bool has_draft = !params.mparams_dft.path.empty();
        bool has_draft_eagle3 = false; // TODO PR-18039: if params.speculative.eagle3

        // A GLM-5.3 MTP draft announces itself through its architecture, so -md is all
        // the user has to pass. Treating it as an ordinary draft model would run it
        // without hidden states and produce noise, so this is a redirect, not an option.
        bool has_mtp = has_draft && common_speculative_is_mtp(params.model_dft);
        if (has_mtp) {
            has_draft = false;
            LOG_INF("%s: draft model is a GLM-5.3 MTP module - using hidden-state speculation\n", __func__);
        }

        bool has_ngram_cache   = (params.type == COMMON_SPECULATIVE_TYPE_NGRAM_CACHE);
        bool has_ngram_simple  = (params.type == COMMON_SPECULATIVE_TYPE_NGRAM_SIMPLE);
        bool has_ngram_map_k   = (params.type == COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K);
        bool has_ngram_map_k4v = (params.type == COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K4V);
        bool has_ngram_mod     = (params.type == COMMON_SPECULATIVE_TYPE_NGRAM_MOD);

        // In a more complex implementation we could use the same implementation but with different parameters.
        // This was initially used in PR-18471 but removed to simplify the code.
        if (has_ngram_simple) {
            // This implementation can guess a lot of tokens without any draft model.
            configs.push_back(common_speculative_config(COMMON_SPECULATIVE_TYPE_NGRAM_SIMPLE, params));
        }
        if (has_ngram_map_k) {
            configs.push_back(common_speculative_config(COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K, params));
        }
        if (has_ngram_map_k4v) {
            // This implementation can guess tokens with high acceptance rate but is more expensive.
            configs.push_back(common_speculative_config(COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K4V, params));
        }
        if (has_ngram_mod) {
            // shared instance for all speculative decoding contexts
            if (!params.ngram_mod) {
                params.ngram_mod = std::make_shared<common_ngram_mod>(params.ngram_size_n, 4*1024*1024);

                LOG_INF("%s: initialized ngram_mod with n=%d, size=%zu (%.3f MB)\n", __func__,
                        params.ngram_size_n, params.ngram_mod->size(),
                        (float)(params.ngram_mod->size_bytes())/1024/1024);

                if (params.ngram_size_n < 16) {
                    LOG_WRN("%s: ngram_mod n=%d is too small - poor quality is possible, see: https://github.com/ggml-org/llama.cpp/pull/19164\n", __func__, params.ngram_size_n);
                }
            }

            configs.push_back(common_speculative_config(COMMON_SPECULATIVE_TYPE_NGRAM_MOD, params));
        }
        if (has_ngram_cache) {
            configs.push_back(common_speculative_config(COMMON_SPECULATIVE_TYPE_NGRAM_CACHE, params));
        }
        if (has_draft) {
            configs.push_back(common_speculative_config(COMMON_SPECULATIVE_TYPE_DRAFT, params));
        }
        if (has_draft_eagle3) {
            configs.push_back(common_speculative_config(COMMON_SPECULATIVE_TYPE_EAGLE3, params));
        }
        if (has_mtp) {
            configs.push_back(common_speculative_config(COMMON_SPECULATIVE_TYPE_MTP, params));
        }
    }

    std::vector<std::unique_ptr<common_speculative_state>> impls = {};

    for (const common_speculative_config & config : configs) {
        LOG_DBG("%s: adding implementation %s\n", __func__, common_speculative_type_to_str(config.type).c_str());
        switch (config.type) {
            case COMMON_SPECULATIVE_TYPE_NONE:
                break;
            case COMMON_SPECULATIVE_TYPE_DRAFT: {
                impls.push_back(std::make_unique<common_speculative_state_draft>(config.type,
                    /* .ctx_tgt      = */ ctx_tgt,
                    /* .ctx_dft      = */ ctx_dft,
                    /* .replacements = */ params.replacements
                ));
                break;
            }
            case COMMON_SPECULATIVE_TYPE_EAGLE3: {
                impls.push_back(std::make_unique<common_speculative_state_eagle3>(config.type));
                break;
            }
            case COMMON_SPECULATIVE_TYPE_MTP: {
                impls.push_back(std::make_unique<common_speculative_state_mtp>(config.type,
                    /* .ctx_tgt = */ ctx_tgt,
                    /* .ctx_dft = */ ctx_dft
                ));
                break;
            }
            case COMMON_SPECULATIVE_TYPE_NGRAM_SIMPLE: {
                common_ngram_map ngram_map = get_common_ngram_map(config);

                uint16_t ngram_size_key   = ngram_map.size_key;
                uint16_t mgram_size_value = ngram_map.size_value;

                auto config_simple = common_ngram_simple_config {
                    /* .size_ngram      = */ ngram_size_key,
                    /* .size_mgram      = */ mgram_size_value
                };
                auto state = std::make_unique<common_speculative_state_ngram_simple>(
                    /* .type            = */ config.type,
                    /* .state           = */ config_simple
                );
                impls.push_back(std::move(state));
                break;
            }
            case COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K:
            case COMMON_SPECULATIVE_TYPE_NGRAM_MAP_K4V: {
                impls.push_back(std::make_unique<common_speculative_state_ngram_map_k>(
                    (config.type),
                    get_common_ngram_map(config)
                ));
                break;
            }
            case COMMON_SPECULATIVE_TYPE_NGRAM_MOD: {
                GGML_ASSERT(config.params.ngram_mod);
                impls.push_back(std::make_unique<common_speculative_state_ngram_mod>(config.type, *config.params.ngram_mod));
                break;
            }
            case COMMON_SPECULATIVE_TYPE_NGRAM_CACHE: {
                auto state = create_state_ngram_cache(
                        params.lookup_cache_static, params.lookup_cache_dynamic, config);
                impls.push_back(std::make_unique<common_speculative_state_ngram_cache>(state));
                break;
            }
            default:
                break;
        }
    }

    if (impls.empty()) {
        LOG_WRN("%s", "no implementations specified for speculative decoding\n");
        return nullptr;
    }

    auto * result = new common_speculative();

    result->impls = std::move(impls);

    // Arm the recurrent-state rollback for targets whose memory cannot drop rejected tokens. The
    // test is on the model rather than on a decode probe: common_speculative_is_compat() has
    // already paid for the probe, and repeating it here would clear the caller's memory.
    {
        const llama_model * model_tgt = llama_get_model(ctx_tgt);

        if (llama_model_is_recurrent(model_tgt) || llama_model_is_hybrid(model_tgt)) {
            result->rb = std::make_unique<common_spec_rollback>(ctx_tgt, seq_id_tgt, (int32_t) llama_n_batch(ctx_tgt));

            LOG_INF("%s: recurrent-state rollback enabled for seq %d (checkpoint %.2f MiB)\n", __func__,
                    seq_id_tgt,
                    llama_state_seq_get_size_ext(ctx_tgt, seq_id_tgt, LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY)/1024.0/1024.0);
        }
    }

    return result;
}

void common_speculative_free(common_speculative * spec) {
    if (spec == nullptr) {
        return;
    }

    delete spec;
}

void common_speculative_begin(common_speculative * spec, const llama_tokens & prompt) {
    if (spec == nullptr) {
        return;
    }

    for (auto & impl : spec->impls) {
        common_time_meas tm(impl->t_begin_us, !impl->gen_perf);
        impl->begin(prompt);
        impl->n_call_begin++;
    }
}

llama_tokens common_speculative_draft(
        common_speculative * spec,
        const common_params_speculative & params,
        const llama_tokens & prompt_tgt, // specified in target model vocab
        llama_token id_last) {
    llama_tokens result;

    spec->curr_impl = nullptr; // reset current implementation

    if (spec->broken) {
        return result;
    }

    // Safety net for a caller that does not flush on its own: the checkpoint below reads the
    // target's write position, and that is only right once the replay has landed.
    common_speculative_flush_rollback(spec);

    for (auto & impl : spec->impls) {
        {
            common_time_meas tm(impl->t_draft_us, !impl->gen_perf);
            impl->draft(params, prompt_tgt, id_last, result);
            impl->n_call_draft++;
        }

        if (!result.empty()) {
            LOG_DBG("%s: called impl %s, hist size = %zu, call_count = %zu, gen = %zu\n", __func__,
                    common_speculative_type_to_str(impl.get()->type).c_str(), prompt_tgt.size(),
                    impl.get()->n_call_draft, result.size());

            spec->curr_impl = impl.get(); // set current implementation for stats
            impl->n_gen_drafts++;
            impl->n_gen_tokens += result.size();

            break; // We have a draft, so break out of the loop and return it.
        }
    }

    // Drop a draft too short to be worth verifying. Both callers already do this on their side,
    // but deciding it here as well is what keeps the checkpoint below in step with what the target
    // is actually fed - a draft discarded after the checkpoint was taken would leave the rollback
    // expecting tokens that never reached the batch.
    if ((int) result.size() < params.n_min) {
        result.clear();
    }

    // The target's memory holds nothing but the committed prefix at this moment, which is the only
    // point at which the checkpoint is worth taking.
    if (spec->rb) {
        if (result.empty()) {
            // Nothing drafted means nothing can be rejected. Disarm rather than leave the previous
            // round's checkpoint armed, which would make the next rollback restore to a stale
            // position.
            spec->rb->armed = false;
        } else {
            common_spec_rollback_save(spec->rb.get(), id_last, result);
        }
    }

    return result;
}

void common_speculative_set_target_output_idx(common_speculative * spec, int32_t i) {
    if (spec == nullptr) {
        return;
    }

    // Applies to whichever implementation is live; the others ignore it.
    for (const auto & impl : spec->impls) {
        impl->set_target_output_idx(i);
    }

    // i is also the number of drafted tokens the target accepted, which is all the rollback needs
    // to know. It has to run after the implementations, not before: the MTP implementation reads
    // the target's hidden state in the call above, and the replay overwrites it.
    if (spec->rb && !common_spec_rollback_apply(spec->rb.get(), i)) {
        LOG_ERR("%s: recurrent-state rollback failed - disabling speculative decoding\n", __func__);
        spec->broken = true;
    }
}

void common_speculative_flush_rollback(common_speculative * spec) {
    if (spec == nullptr || spec->rb == nullptr || spec->broken) {
        return;
    }

    if (!common_spec_rollback_flush(spec->rb.get())) {
        LOG_ERR("%s: recurrent-state replay failed - disabling speculative decoding\n", __func__);
        spec->broken = true;
    }
}

void common_speculative_accept(common_speculative * spec, uint16_t n_accepted) {
    if (n_accepted == 0) {
        return;
    }

    common_speculative_state * impl = spec->curr_impl;

    GGML_ASSERT(impl);

    {
        common_time_meas tm(impl->t_accept_us, !impl->gen_perf);
        if (n_accepted > 0) {
            impl->n_acc_drafts++;
            impl->n_acc_tokens += n_accepted;
        }

        impl->accept(n_accepted);
        impl->n_call_accept++;
    }
}

void common_speculative_print_stats(const common_speculative * spec) {
    if (spec == nullptr) {
        return;
    }

    for (const auto & impl : spec->impls) {
        std::string str_perf;
        if (impl->gen_perf) {
            std::ostringstream oss;
            oss << std::fixed << std::setprecision(3) << impl->t_begin_us / 1000.0 << ", ";
            oss << std::fixed << std::setprecision(3) << impl->t_draft_us / 1000.0 << ", ";
            oss << std::fixed << std::setprecision(3) << impl->t_accept_us / 1000.0;
            str_perf = ", dur(b,g,a) = " + oss.str() + " ms";
        } else {
            str_perf = "";
        }

        LOG_INF("statistics %s: #calls(b,g,a) = %zu %zu %zu, #gen drafts = %zu, #acc drafts = %zu, #gen tokens = %zu, #acc tokens = %zu%s\n",
                common_speculative_type_to_str(impl->type).c_str(),
                impl->n_call_begin, impl->n_call_draft, impl->n_call_accept,
                impl->n_gen_drafts,
                impl->n_acc_drafts,
                impl->n_gen_tokens,
                impl->n_acc_tokens,
                str_perf.c_str());
    }
}
